import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

const fontLabels: Record<string, string> = {
  TwobPencilLine: "Lápis Criativo 2B",
  AMORE: "Amor & Alegria",
  Bagel: "Bagel Divertido",
  Baligo_Regular: "Baligo Básico",
  CoffeeExtra: "Café Extra Forte",
  CuteDropCaps: "Capsule Charmosa",
  DearCrush: "Querido Crush",
  DigitalPlannerFontRegular: "Planejador Digital",
  FINESHADOWS: "Sombras Finas",
  font_669fd58456d67: "Comic Descolada",
  font_66a2b77b6e6f6: "Vibe Relax",
  font_66ad1eb8606ed: "Queijo Quirky",
  font_66ad1eb870a7e: "Fresco Funky",
  font_66ad1eb873176: "Riff Retrô",
  font_66afdaed4203d: "Rabiscos Sassy",
  font_66b5150a1b9c6: "Pixels Divertidos",
  font_66b5150a24650: "Banana Bold",
  font_66b5150a2d3bb: "Charme Witty",
  font_66b5150a8247b: "Script Estiloso",
  font_66ba5e2a1cef0: "Chocolate Alegre",
  font_66ba5e2ab1c91: "Delícia Doodle",
  font_66ba5e2ab6772: "Grafite Groovy",
  font_66ba5e2abb8a0: "Hipster Feliz",
  font_66ba5e2b4d016: "Giz Charmoso",
  font_66ba5e2b61722: "Zest Energético",
  font_66ba5e2b78f19: "Anotador Jolly",
  font_66ba5e2b86d6f: "Pena Funky",
  font_66bf7f44e4e24: "Pintura Spunky",
  font_66bf7f459b0db: "Comic Crocante",
  font_66bf7f45c5e82: "Jive Alegre",
  font_66bf7f45ea07d: "Pop Empolgante",
  font_66bfb59032cad: "Rabisco Vivo",
  font_66c2833ac4adf: "Graffiti Animado",
  font_66c2833b17f8f: "Fresco Giddy",
  font_66c60bf7c6f75: "Vibe Alegre",
  font_66cb85a5b787e: "Pop Energético",
  font_66cb85a5c989b: "Rabisco Irreverente",
  font_66cb85a67f901: "Divertido Crispy",
  font_66d0a3bdd215e: "Grafite Leve",
  GorilazyRegular: "Gorila Relax",
  HeyBunny: "Oi Coelhinho",
  LagetonScript: "Lageton Script",
  NiceBroyRegular: "Nice Broy",
  OneStory: "História Única",
  Phitaya: "Phitaya",
  SAFunJoJoSymbols: "JoJo Símbolos",
  SAFunJoJo: "JoJo Divertido",
  Saturday_Lunchtime: "Sábado Almoço",
  SheisMineDemo: "Ela É Minha",
  Siloam: "Siloam",
  Simple: "Simples e Legal",
  SimplifyNotationSingleLine: "Notação Simples",
  SmileWorld: "Mundo Sorriso",
  SummerVintage: "Verão Vintage",
  SuperFriendPersonalUse: "Amigo Super Pessoal",
  SweetNote: "Nota Doce",
  Tangle: "Desembaraçar",
  Toys_Cutes: "Brinquedos Fofos",
  TuckShop_Outline: "Tuck Shop",
  Winter_Princess: "Princesa do Inverno",
  You_Are_My_Valentine: "Você É Meu Valentine",
  aBençoadaEcriativa: "Abençoada e criativa",
  aCabouApipoca: "Acabou a pipoca",
  achadinho: "Achandinha",
  amoCafeDeHotel: "Amo café de hotel",
  amoMacadamia: "Amo macadamia",
  amoMarshmallow: "Amo marshmallow",
  amore: "Amore",
  ANotificaçãoQueEuAmo: "A notificação que eu amo",
  aNovaFavorita: "A nova favorita",
  aTerapiaEmDia: "A terapia em dia",
  aTerapiaQueEuGosto: "A terapia que eu gosto",
  atrasadinha: "Atrasadinha",
  autoCuidado: "Auto cuidado",
  basicLove: "Basic Love",
  banhoMatinal: "Banho Matinal",
  bemEngracadinha: "Bem engraçadinho",
  bomDiaTodoDia: "Bom dia todo dia",
  cafeSemAcucar: "Café sem açucar",
  deGizEmGiz: "De Giz em Giz",
  euQuero: "Eu quero",
  eleganteAndFinissima: "Elegante e finissima",
  storyNovo: "Story Novo",
  storySlim: "Story Slim",
  ativaDescanso: "Ativa Descanso",
  confyAndInadivel: "Confy and Inadivel",
  cool: "Cool",
  Simplify: "simplify",
};

export async function GET() {
  const fontsDir = path.join(process.cwd(), "public/fonts");
  const fontFiles = fs.readdirSync(fontsDir);
  const fonts = fontFiles.map((fileName) => ({
    label: path.basename(fileName, path.extname(fileName)),
    fontName: fontLabels[path.basename(fileName, path.extname(fileName))],
    value: `fonts/${fileName}`,
  }));

  return NextResponse.json(fonts);
}
